program = { statement } ;

statement = declStmt | exprStmt ;

declStmt = varDecl | funDecl ;
varDecl = { annotation } "let" IDENTIFIER "=" expression ";" ;

exprStmt = expression ";" ;

annotation = "@" STRING ;
