program = { statement } ;

statement = decl_stmt | expr_stmt ;

decls_tmt = { annotation " " } var_decl | fun_decl ;

var_decl = "let" IDENTIFIER "=" expression ";" ;

fun_decl = "fun" IDENTIFIER "(" [ parameters ] ")" [ "->" TYPE ] ( "=" expression | ";" ) ;
parameters = IDENTIFIER ":" TYPE { "," IDENTIFIER ":" TYPE } ;

expr_stmt = expression ";" ;

annotation = "@" STRING ;
